import type { StoreTheme } from "./theme";
import type { TemplateId } from "./types";

const base: Omit<StoreTheme, "template"> = {
  accentColor: "#FF4D6D",
  backgroundColor: "#080808",
  surfaceColor: "#111111",
  textPrimaryColor: "#ffffff",
  textSecondaryColor: "#888888",
  buttonTextColor: "#ffffff",
  backgroundType: "solid",
  fontHeading: "Plus Jakarta Sans",
  fontBody: "DM Sans",
  nameSize: "md",
  nameWeight: 700,
  nameTransform: "none",
  nameLetterSpacing: "tight",
  avatarShape: "circle",
  avatarSize: "md",
  avatarBorderWidth: 0,
  avatarBorderColor: "#FF4D6D",
  avatarShadow: false,
  storeLayout: "list",
  pageMaxWidth: "compact",
  cardBorderRadius: "md",
  cardBorderWidth: 1,
  cardBorderColor: "rgba(255,255,255,0.06)",
  cardShadow: "none",
  cardShadowColor: "rgba(0,0,0,0.18)",
  showProductDescription: true,
  showProductRating: false,
  cardLayout: "cover-left",
  coverHeight: "sm",
  buttonStyle: "filled",
  buttonRadius: "md",
  buttonSize: "md",
  buttonWeight: 600,
  buttonTransform: "none",
  linkStyle: "icon-only",
  linkSize: "sm",
  separatorStyle: "accent-line",
  separatorWidth: "short",
  themeMode: "dark",
};

export const THEME_PRESETS: Record<TemplateId, StoreTheme> = {
  minimal: {
    ...base,
    template: "minimal",
    cardLayout: "cover-top",
    coverHeight: "md",
    storeLayout: "grid1",
  },
  cards: {
    ...base,
    template: "cards",
    storeLayout: "grid2",
    cardLayout: "cover-top",
    cardBorderRadius: "lg",
    coverHeight: "md",
    buttonRadius: "md",
    showProductDescription: false,
    cardShadow: "md",
    cardShadowColor: "rgba(0,0,0,0.35)",
  },
  glass: {
    ...base,
    template: "glass",
    accentColor: "#818CF8",
    avatarBorderColor: "rgba(255,255,255,0.2)",
    backgroundType: "mesh",
    backgroundColor: "#0f0f1a",
    backgroundGradient: { from: "#0f0f1a", to: "#7C3AED", angle: 135 },
    surfaceColor: "rgba(255,255,255,0.06)",
    cardBorderColor: "rgba(255,255,255,0.14)",
    cardBorderRadius: "lg",
    coverHeight: "md",
    cardShadow: "lg",
    cardShadowColor: "rgba(0,0,0,0.35)",
    avatarShadow: true,
    storeLayout: "grid2",
    cardLayout: "cover-top",
    buttonStyle: "ghost",
    linkStyle: "pill",
  },
  bold: {
    ...base,
    template: "bold",
    accentColor: "#FFFFFF",
    backgroundColor: "#000000",
    surfaceColor: "#0d0d0d",
    textPrimaryColor: "#ffffff",
    textSecondaryColor: "#666666",
    buttonTextColor: "#000000",
    fontHeading: "Bebas Neue",
    fontBody: "Space Grotesk",
    nameSize: "xl",
    nameWeight: 900,
    nameTransform: "uppercase",
    nameLetterSpacing: "wider",
    avatarShape: "square",
    avatarSize: "lg",
    avatarBorderWidth: 4,
    avatarBorderColor: "#ffffff",
    storeLayout: "grid2",
    cardLayout: "cover-top",
    coverHeight: "md",
    cardBorderRadius: "none",
    buttonRadius: "none",
    buttonWeight: 900,
    buttonTransform: "uppercase",
    linkStyle: "text-only",
    separatorStyle: "line",
    separatorWidth: "full",
  },
  magazine: {
    ...base,
    template: "magazine",
    accentColor: "#1a1a1a",
    backgroundColor: "#F4F1EA",
    surfaceColor: "#FFFDF8",
    textPrimaryColor: "#181614",
    textSecondaryColor: "#5F5A52",
    buttonTextColor: "#ffffff",
    themeMode: "light",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    pageMaxWidth: "medium",
    cardLayout: "cover-top",
    coverHeight: "md",
    cardBorderColor: "rgba(24,22,20,0.12)",
    cardShadow: "sm",
    cardShadowColor: "rgba(24,22,20,0.08)",
    linkStyle: "text-only",
    separatorStyle: "line",
  },
  retro: {
    ...base,
    template: "retro",
    accentColor: "#FF6B2B",
    backgroundColor: "#FFF8E7",
    surfaceColor: "#fff2d0",
    textPrimaryColor: "#111111",
    textSecondaryColor: "#666666",
    buttonTextColor: "#ffffff",
    themeMode: "light",
    fontHeading: "Syne",
    fontBody: "Syne",
    avatarBorderWidth: 4,
    avatarBorderColor: "#000000",
    avatarShadow: true,
    cardBorderWidth: 2,
    cardBorderColor: "#000000",
    coverHeight: "md",
    cardShadow: "md",
    cardShadowColor: "#000000",
    cardBorderRadius: "sm",
    storeLayout: "grid2",
    cardLayout: "cover-top",
    buttonRadius: "sm",
    linkStyle: "pill",
  },
  soft: {
    ...base,
    template: "soft",
    accentColor: "#FF7A5C",
    backgroundColor: "#FFF3EE",
    surfaceColor: "#FFFDFC",
    textPrimaryColor: "#1f1714",
    textSecondaryColor: "#8a746b",
    buttonTextColor: "#ffffff",
    themeMode: "light",
    fontHeading: "Nunito",
    fontBody: "Nunito",
    nameSize: "lg",
    nameWeight: 800,
    avatarSize: "lg",
    avatarBorderWidth: 4,
    avatarBorderColor: "#FF7A5C",
    avatarShadow: true,
    storeLayout: "grid1",
    cardLayout: "cover-top",
    coverHeight: "md",
    cardBorderRadius: "xl",
    cardBorderWidth: 1,
    cardBorderColor: "rgba(255,122,92,0.18)",
    cardShadow: "sm",
    cardShadowColor: "rgba(139,79,57,0.10)",
    buttonRadius: "pill",
    linkStyle: "pill",
  },
  cleanpro: {
    ...base,
    template: "cleanpro",
    accentColor: "#2563EB",
    backgroundColor: "#F3F4F6",
    surfaceColor: "#ffffff",
    textPrimaryColor: "#111827",
    textSecondaryColor: "#4B5563",
    buttonTextColor: "#ffffff",
    themeMode: "light",
    fontHeading: "Inter",
    fontBody: "Inter",
    nameSize: "sm",
    nameWeight: 600,
    pageMaxWidth: "medium",
    cardLayout: "cover-top",
    coverHeight: "md",
    storeLayout: "grid1",
    cardBorderRadius: "md",
    cardBorderColor: "rgba(15,23,42,0.10)",
    cardShadow: "sm",
    cardShadowColor: "rgba(15,23,42,0.06)",
    linkStyle: "icon-only",
    separatorStyle: "none",
  },
};

export const themePresetIds: TemplateId[] = ["minimal", "cards", "glass", "bold", "magazine", "retro", "soft", "cleanpro"];

