import type { Creator, Metrics, MockUser, Product, Sale } from "@/lib/types";
import { THEME_PRESETS } from "@/lib/theme-presets";

export const landingCreator: Creator = {
  name: "Ana Fitness",
  username: "anafitness",
  bio: "Personal trainer | Treinos e planilhas",
  avatarColor: "#FF4D6D",
  accentColor: "#FF4D6D",
  template: "cards",
  theme: THEME_PRESETS.cards,
  coverImage: null,
  presentationVideo: {
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    showThumbnail: true,
    caption: "Assista antes de comprar 👇",
  },
  announcement: {
    enabled: false,
    text: "",
    background: "rgba(255,77,109,0.10)",
    border: "rgba(255,77,109,0.30)",
  },
  links: [
    { id: "1", type: "instagram", label: "Instagram", url: "https://instagram.com/anafitness" },
    { id: "2", type: "tiktok", label: "TikTok", url: "https://tiktok.com/@anafitness" },
    { id: "3", type: "youtube", label: "YouTube", url: "https://youtube.com/@anafitness" },
    { id: "4", type: "whatsapp", label: "WhatsApp", url: "https://wa.me/5521999999999" },
    { id: "5", type: "website", label: "Meu site", url: "https://anafitness.com.br" },
  ],
  socials: {
    instagram: "https://instagram.com/anafitness",
    tiktok: "https://tiktok.com/@anafitness",
    youtube: "https://youtube.com/@anafitness",
  },
};

const baseReviews = [
  {
    id: "r1",
    author: "Maria Souza",
    avatar: "#FF4D6D",
    rating: 5,
    text: "Conteúdo direto ao ponto, bem organizado e fácil de aplicar na rotina. Valeu muito.",
    date: "há 3 dias",
    verified: true,
  },
  {
    id: "r2",
    author: "João Lima",
    avatar: "#22C55E",
    rating: 5,
    text: "Recebi tudo no email poucos minutos depois do pagamento. Material caprichado.",
    date: "há 1 semana",
    verified: true,
  },
  {
    id: "r3",
    author: "Camila Rocha",
    avatar: "#38BDF8",
    rating: 4,
    text: "Gostei bastante da explicação e dos exemplos. Já comecei a usar no mesmo dia.",
    date: "há 2 semanas",
    verified: true,
  },
  {
    id: "r4",
    author: "Rafa Martins",
    avatar: "#F59E0B",
    rating: 5,
    text: "Produto melhor do que eu esperava. A Ana explica de um jeito muito prático.",
    date: "há 1 mês",
    verified: true,
  },
];

const treinoReviews = [
  {
    id: "treino-r1",
    author: "Bruna Almeida",
    avatar: "#FF4D6D",
    rating: 5,
    text: "Ja testei varias planilhas de treino e essa foi a primeira que consegui seguir sem me perder. A progressao semanal ajuda muito.",
    date: "2026-05-28",
    verified: true,
  },
  {
    id: "treino-r2",
    author: "Lucas Ferreira",
    avatar: "#10B981",
    rating: 5,
    text: "Uso na academia e ficou muito facil controlar carga e repeticoes. Em quatro semanas ja senti evolucao real.",
    date: "2026-05-20",
    verified: true,
  },
  {
    id: "treino-r3",
    author: "Paula Nunes",
    avatar: "#7C3AED",
    rating: 4,
    text: "Gostei bastante da divisao dos treinos. So senti falta de mais videos de execucao, mas a planilha e muito boa.",
    date: "2026-05-11",
    verified: true,
  },
  {
    id: "treino-r4",
    author: "Marcos Vinicius",
    avatar: "#06B6D4",
    rating: 5,
    text: "Treino em casa e consegui adaptar tudo com os equipamentos que tenho. Material bem organizado.",
    date: "2026-04-24",
    verified: false,
  },
  {
    id: "treino-r5",
    author: "Renata Lima",
    avatar: "#F59E0B",
    rating: 5,
    text: "A planilha me deu constancia. Antes eu mudava treino toda semana, agora sei exatamente o que fazer.",
    date: "2026-04-10",
    verified: true,
  },
];

const ebookReviews = [
  {
    id: "ebook-r1",
    author: "Juliana Costa",
    avatar: "#10B981",
    rating: 5,
    text: "As receitas sao simples e nao usam ingredientes impossiveis. Consegui montar cardapio para a semana inteira.",
    date: "2026-05-30",
    verified: true,
  },
  {
    id: "ebook-r2",
    author: "Carla Mendes",
    avatar: "#FF4D6D",
    rating: 5,
    text: "Gostei das substituicoes. Foi o que mais me ajudou a nao sair da dieta no fim de semana.",
    date: "2026-05-18",
    verified: true,
  },
  {
    id: "ebook-r3",
    author: "Diego Ramos",
    avatar: "#06B6D4",
    rating: 4,
    text: "Bem explicado e direto. Algumas receitas eu ja conhecia, mas a organizacao do ebook valeu a compra.",
    date: "2026-05-06",
    verified: false,
  },
  {
    id: "ebook-r4",
    author: "Nathalia Prado",
    avatar: "#7C3AED",
    rating: 5,
    text: "O guia de macros e a lista de compras salvaram minha rotina. Material muito pratico.",
    date: "2026-04-19",
    verified: true,
  },
];

const packReviews = [
  {
    id: "pack-r1",
    author: "Bianca Torres",
    avatar: "#06B6D4",
    rating: 5,
    text: "Os stories ficaram com cara muito mais profissional. Editei tudo no Canva em menos de uma hora.",
    date: "2026-05-25",
    verified: true,
  },
  {
    id: "pack-r2",
    author: "Felipe Rocha",
    avatar: "#F59E0B",
    rating: 5,
    text: "Usei os modelos de oferta no lancamento do meu ebook e melhorou muito a apresentacao.",
    date: "2026-05-14",
    verified: true,
  },
  {
    id: "pack-r3",
    author: "Thais Cardoso",
    avatar: "#FF4D6D",
    rating: 4,
    text: "Gostei da variedade e das paletas. Alguns layouts exigem mais ajuste, mas o pack e bem completo.",
    date: "2026-04-29",
    verified: false,
  },
  {
    id: "pack-r4",
    author: "Rafael Diniz",
    avatar: "#10B981",
    rating: 5,
    text: "Economizou muito tempo. Ja deixei uma semana inteira de stories prontos.",
    date: "2026-04-12",
    verified: true,
  },
];

const mentoriaReviews = [
  {
    id: "mentoria-r1",
    author: "Amanda Reis",
    avatar: "#FF4D6D",
    rating: 5,
    text: "A Ana foi muito objetiva e montou um plano possivel para minha rotina. Sai da chamada sabendo exatamente o que fazer.",
    date: "2026-05-27",
    verified: true,
  },
  {
    id: "mentoria-r2",
    author: "Victor Hugo",
    avatar: "#7C3AED",
    rating: 5,
    text: "A analise individual fez diferenca. Ajustamos treino e alimentacao sem radicalismo.",
    date: "2026-05-09",
    verified: true,
  },
  {
    id: "mentoria-r3",
    author: "Sofia Martins",
    avatar: "#10B981",
    rating: 5,
    text: "Gostei do resumo enviado depois da chamada. Isso me ajudou a executar sem esquecer os pontos principais.",
    date: "2026-04-28",
    verified: true,
  },
  {
    id: "mentoria-r4",
    author: "Gustavo Leal",
    avatar: "#F59E0B",
    rating: 4,
    text: "Foi uma sessao muito boa e pratica. Queria que tivesse opcao de pacote com acompanhamento mensal.",
    date: "2026-04-16",
    verified: false,
  },
];

export const landingProducts: Product[] = [
  {
    id: "treino-12-semanas",
    name: "Planilha de Treino 12 semanas",
    price: 4700,
    originalPrice: 9700,
    type: "planilha",
    coverColor: "#FF4D6D",
    description: "Rotina completa para evoluir no treino em casa ou academia, com progressão semanal e acompanhamento simples.",
    includes: [
      "12 semanas de treino estruturado",
      "Progressão de cargas semana a semana",
      "Versão para academia e casa",
      "Checklist de execução dos treinos",
      "Suporte por 30 dias",
    ],
    reviews: treinoReviews,
    active: true,
    status: "active",
    featured: true,
    sales: 18,
    revenue: 84600,
    coverGradient: ["#064e3b", "#065f46"],
    shortDescription: "Treino de 12 semanas com progressão simples.",
    deliveryPlatform: "Excel (.xlsx)",
    compatibleWith: ["PC", "Mac", "Celular"],
    upsell: {
      productId: "ebook-low-carb",
      price: 1900,
      originalPrice: 2700,
      buttonText: "Sim, quero o combo completo!",
      discount: 30,
    },
  },
  {
    id: "ebook-low-carb",
    name: "Ebook Dieta Low Carb",
    price: 2700,
    originalPrice: 5700,
    type: "ebook",
    coverColor: "#22C55E",
    description: "Receitas práticas para reduzir carboidratos sem complicação, com cardápios simples para a semana.",
    includes: [
      "40 receitas low carb fáceis",
      "Lista de compras semanal",
      "Sugestões de substituições",
      "Cardápio de 7 dias",
      "Guia rápido de macros",
    ],
    reviews: ebookReviews,
    active: true,
    status: "active",
    sales: 12,
    revenue: 32400,
    coverGradient: ["#1e3a5f", "#1e4d3f"],
    shortDescription: "Receitas low carb práticas para a semana.",
    deliveryPlatform: "Link externo",
    deliveryUrl: "https://drive.google.com/ebook-low-carb",
    pages: 82,
    language: "Português",
    level: "Iniciante",
  },
  {
    id: "stories-editaveis",
    name: "Pack de Stories Editáveis",
    price: 3700,
    type: "pack",
    coverColor: "#38BDF8",
    description: "Templates editáveis para vender melhor nos stories e deixar sua comunicação visual mais profissional.",
    includes: [
      "60 templates editáveis",
      "Modelos para oferta e prova social",
      "Paletas prontas para nichos digitais",
      "Guia de uso no Canva",
      "Atualizações por 60 dias",
    ],
    reviews: packReviews,
    active: true,
    status: "draft",
    featured: false,
    sales: 7,
    revenue: 25900,
    coverGradient: ["#082f49", "#0c4a6e"],
    shortDescription: "Pack editável para vender melhor nos stories.",
    fileCount: 60,
    fileTypes: ["JPG/PNG", "PDF", "ZIP"],
    totalSize: "50-200MB",
    license: "Uso comercial",
  },
  {
    id: "mentoria-video",
    name: "Mentoria 1h por Vídeo",
    price: 19700,
    originalPrice: 29700,
    type: "mentoria",
    coverColor: "#F59E0B",
    description: "Sessão individual para montar seu plano de treino e dieta com orientação prática para sua rotina.",
    includes: [
      "1 hora de chamada individual",
      "Análise da sua rotina atual",
      "Plano inicial personalizado",
      "Gravação da chamada",
      "Resumo por email com próximos passos",
    ],
    reviews: mentoriaReviews,
    active: false,
    status: "hidden",
    sales: 4,
    revenue: 78800,
    coverGradient: ["#500724", "#4a044e"],
    shortDescription: "Mentoria individual por vídeo para montar seu plano.",
    sessionDuration: "1h",
    sessionFormat: "Google Meet",
    schedulingMethod: "Calendly (link)",
    schedulingValue: "https://calendly.com/anafitness/mentoria",
    availability: "Seg/Qua/Sex das 14h às 18h",
    recordingIncluded: true,
    seats: 3,
  },
];

export const mockSales: Sale[] = [
  {
    id: "#1048",
    product: "Mentoria 1h por Vídeo",
    buyer: "maria.souza@email.com",
    value: 19700,
    method: "Mercado Pago",
    date: "Hoje, 09:42",
    status: "Pago",
    upsellProductId: "ebook-low-carb",
    upsellValue: 1900,
  },
  {
    id: "#1047",
    product: "Planilha de Treino 12 semanas",
    buyer: "joao.fit@gmail.com",
    value: 4700,
    method: "Mercado Pago",
    date: "Hoje, 08:18",
    status: "Pago",
    upsellProductId: "ebook-low-carb",
    upsellValue: 1900,
  },
  {
    id: "#1046",
    product: "Ebook Dieta Low Carb",
    buyer: "camila.nutri@hotmail.com",
    value: 2700,
    method: "Mercado Pago",
    date: "Ontem, 22:11",
    status: "Pendente",
  },
  {
    id: "#1045",
    product: "Pack de Stories Editáveis",
    buyer: "bia.creator@email.com",
    value: 3700,
    method: "Mercado Pago",
    date: "Ontem, 17:32",
    status: "Pago",
  },
  {
    id: "#1044",
    product: "Planilha de Treino 12 semanas",
    buyer: "rafael.run@gmail.com",
    value: 4700,
    method: "Mercado Pago",
    date: "Ter, 14:08",
    status: "Pago",
  },
  {
    id: "#1043",
    product: "Ebook Dieta Low Carb",
    buyer: "livia.health@email.com",
    value: 2700,
    method: "Mercado Pago",
    date: "Seg, 11:03",
    status: "Pago",
  },
  {
    id: "#1042",
    product: "Mentoria 1h por Vídeo",
    buyer: "andre.persona@gmail.com",
    value: 19700,
    method: "Mercado Pago",
    date: "Dom, 19:21",
    status: "Pendente",
  },
];

export const mockMetrics: Metrics = {
  totalRevenue: 124700,
  todayRevenue: 19700,
  visitors: 342,
  conversion: 3.2,
};

export const mockUser: MockUser = {
  name: "Ana Fitness",
  email: "ana@fitness.com",
  username: "anafitness",
  avatar: null,
  plan: "free",
  payoutDestination: { type: "mercadopago", value: "Conta Mercado Pago conectada" },
  bankData: {
    bank: "Nubank",
    accountType: "Corrente",
    agency: "0001-0",
    account: "12345-6",
    document: "123.456.789-00",
    holder: "Ana Fitness",
  },
  balance: { available: 84730, pending: 19700 },
  notifications: {
    newSale: true,
    pixExpired: true,
    dailySummary: false,
    weeklySummary: false,
    productNews: true,
    whatsappEnabled: false,
    whatsappNumber: "",
    pushEnabled: false,
  },
  integrations: {
    metaPixel: null,
    googleAnalytics: null,
    tiktokPixel: null,
    webhook: null,
  },
  domain: { custom: null, status: null },
};

export const mockChartData = [
  { day: "Seg", value: 240 },
  { day: "Ter", value: 420 },
  { day: "Qua", value: 380 },
  { day: "Qui", value: 620 },
  { day: "Sex", value: 540 },
  { day: "Sáb", value: 790 },
  { day: "Dom", value: 680 },
];

